#日志配置
logging:
  level:
    cn.ruiyeclub: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wdog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    #boot2.X使用lettuce作为连接池
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 10000
  aop:
    proxy-target-class: true
    auto: true

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 1000

swagger:
  enabled: true
  pathMapping: